### ISSUE TITLE
Opening an SVG gives random noise

### ISSUE THREAD

**Issue by uellue** [matbryan52/image-viewer#12]
## How to reproduce

https://moellenstedt.iff.kfa-juelich.de/user-redirect/image-viewer/?path=%2Fstorage%2Fer-c-data%2Fadhoc%2Fvadimpcm%2Fpaper%2Fprocessing%2Fcrystallography%2Fpeakassignment.svg&redirects=1

## What happens

I get an array of random noise.

## What should happen

The SVG image or a helpful error message (format not supported and such) is shown.

**Comment by matbryan52** [comment]
Thanks for the report. The random noise is the fallback when either `rosettasciio` or `skimage` can't load the requested data, which is the case for SVG files. When I work on #13 you would hopefully get an error message instead.

That said, Panel does support SVG display so we can add another code path to display SVG files using their widget rather than the `LiberTEM-panel-ui` implementation which only works on raster data.
